apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: back-end
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Luis-Diaz-Cryo/parcial-1LDiaz.git
    path: "Patrones-parcial"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: back-end
