apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  labels:
    app: back-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-end
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        - image: 'cyldecryo/parcial-1-patrones:8417f6fc69b21fe505a615eade68ca318bb4a6a4'
          name: back-end
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: back-end
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090
  selector:
    app: back-end
  template:
    spec:
      containers:
        - image: cyldecryo/parcial-1-patrones:8417f6fc69b21fe505a615eade68ca318bb4a6a4
