apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  labels:
    app: back-end
spec:
  selector:
    matchLabels:
      app: back-end
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        - image: 'cyldecryo/parcial-1-patrones:0.0.0'
          name: back-end
          ports:
            - containerPort: 3000
