apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  labels:
    app: back-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-end
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        - image: 'cyldecryo/parcial-1-patrones:86e16b7326ce88adc6b269cff03fb10bb54f73f9'
          name: back-end
          ports:
            - containerPort: 9090
