apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - image: 'cyldecryo/parcial-1-patrones:0.0.0'
          name: front-end
          ports:
            - containerPort: 3000
